name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install GO
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.4'

      - name: GO Tidy
        run: go mod tidy

      - name: Build GO
        run: go build -o test ./cmd

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: scp -o StrictHostKeyChecking=no test ubuntu@ec2-3-104-64-171.ap-southeast-2.compute.amazonaws.com

      - name: SSH into EC2 and restart service
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-104-64-171.ap-southeast-2.compute.amazonaws.com << 'EOF'
            cd /deploy-frontend/cmd/
            # Stop the current application process if running (optional)
            pkill -f test || true
            # Start the application
            nohup ./test &
          EOF
