name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install GO
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.4'

      - name: GO Tidy
        run: go mod tidy

      - name: Build GO
        run: go build -o test

      - name: Run GO
        run: ./test
